/**
 * Extra searchable text per Cryptofonts SVG basename (lowercase key, no `.svg`).
 * Lets users find icons by token name (e.g. "bitcoin" → btc), not only the slug.
 * Keys should match filenames in https://github.com/Cryptofonts/cryptoicons/tree/master/SVG
 */
const ICON_NAME_TAGS: Record<string, string> = {
  xu3o8: "uranium xu3o8 u3o8 parkswap txpark",
  vnxau: "vnx gold vnxau gold vnx",
  btc: "bitcoin",
  eth: "ethereum ether",
  xtz: "tezos",
  ltc: "litecoin",
  bch: "bitcoin cash",
  bsv: "bitcoin sv",
  xrp: "ripple",
  ada: "cardano",
  doge: "dogecoin doge coin",
  sol: "solana",
  dot: "polkadot",
  matic: "polygon matic",
  pol: "polygon",
  avax: "avalanche",
  atom: "cosmos",
  near: "near protocol",
  ftm: "fantom",
  algo: "algorand",
  xlm: "stellar lumens",
  vet: "vechain ve chain",
  icp: "internet computer",
  fil: "filecoin",
  trx: "tron tronix",
  eos: "eos",
  xmr: "monero",
  zec: "zcash z cash",
  dash: "dash",
  link: "chainlink",
  uni: "uniswap",
  aave: "aave",
  mkr: "maker",
  comp: "compound",
  snx: "synthetix",
  crv: "curve",
  ldo: "lido",
  ape: "apecoin ape coin",
  sand: "sandbox",
  mana: "decentraland",
  axs: "axie infinity",
  grt: "the graph graph",
  ens: "ethereum name service",
  op: "optimism",
  arb: "arbitrum",
  imx: "immutable immutable x",
  rndr: "render render network",
  inj: "injective injective protocol",
  sui: "sui",
  sei: "sei",
  tia: "celestia",
  apt: "aptos",
  strk: "starknet stark net starkware",
  wld: "worldcoin world coin",
  pepe: "pepe meme",
  shib: "shiba inu shiba",
  floki: "floki",
  bonk: "bonk",
  wif: "dogwifhat dog wif hat",
  usdc: "usd coin circle",
  usdt: "tether",
  dai: "dai makerdao",
  busd: "binance usd binanceusd",
  tusd: "trueusd true usd",
  gusd: "gemini dollar",
  paxg: "pax gold",
  xaut: "tether gold gold token",
  wbtc: "wrapped bitcoin",
  weth: "wrapped ether ethereum",
  steth: "lido staked ether staked eth",
  reth: "rocket pool eth rocket pool",
  frax: "frax",
  lusd: "liquity usd liquity",
  usdp: "pax dollar paxos",
  pyusd: "paypal usd paypal",
  eurt: "euro tether",
  eurs: "stasis euro",
  jpy: "japanese yen",
  gbp: "british pound sterling",
  chf: "swiss franc",
  cad: "canadian dollar",
  aud: "australian dollar",
  nzd: "new zealand dollar",
  sek: "swedish krona",
  nok: "norwegian krone",
  dkk: "danish krone",
  pln: "polish zloty",
  huf: "hungarian forint",
  czk: "czech koruna",
  ron: "romanian leu",
  bgn: "bulgarian lev",
  hrk: "croatian kuna",
  try: "turkish lira",
  rub: "russian ruble",
  uah: "ukrainian hryvnia",
  ils: "israeli shekel",
  aed: "uae dirham",
  sar: "saudi riyal",
  krw: "south korean won",
  twd: "taiwan dollar",
  sgd: "singapore dollar",
  hkd: "hong kong dollar",
  inr: "indian rupee",
  idr: "indonesian rupiah",
  myr: "malaysian ringgit",
  php: "philippine peso",
  thb: "thai baht",
  vnd: "vietnamese dong",
  brl: "brazilian real",
  mxn: "mexican peso",
  ars: "argentine peso",
  clp: "chilean peso",
  cop: "colombian peso",
  pen: "peruvian sol",
  zar: "south african rand",
  ngn: "nigerian naira",
  kes: "kenyan shilling",
  egp: "egyptian pound",
  xof: "west african cfa",
  xaf: "central african cfa",
  bnb: "binance coin binance",
  cro: "cronos crypto com",
  okb: "okx okex",
  kcs: "kucoin",
  htm: "huobi token",
  leo: "bitfinex leo",
  ftt: "ftx token",
  cake: "pancakeswap pancake",
  "1inch": "1inch",
  sushi: "sushiswap sushi",
  yfi: "yearn",
  bal: "balancer",
  knc: "kyber",
  zrx: "0x protocol",
  bat: "basic attention token brave",
  zil: "zilliqa",
  iost: "iost",
  ont: "ontology",
  qtum: "qtum",
  waves: "waves",
  ksm: "kusama",
  rose: "oasis network oasis",
  celo: "celo",
  one: "harmony",
  flow: "flow",
  theta: "theta network",
  tfuel: "theta fuel",
  hot: "holo holochain",
  iota: "iota miota",
  nano: "nano",
  xem: "nem",
  sc: "siacoin sia",
  dcr: "decred",
  rvn: "ravencoin",
  zen: "horizen",
  xvg: "verge",
  steem: "steem",
  hive: "hive",
  wax: "wax",
  enj: "enjin",
  gala: "gala games",
  chz: "chiliz socios",
  lrc: "loopring",
  zks: "zksync",
  mina: "mina protocol",
  celr: "celer network",
  skl: "skale",
  band: "band protocol band",
  api3: "api3",
  ogn: "origin protocol",
  storj: "storj",
  ar: "arweave",
  ocean: "ocean protocol",
  fet: "fetch ai artificial intelligence",
  agix: "singularitynet singularity",
  rpl: "rocket pool",
  ssv: "ssv network",
  cbeth: "coinbase staked eth",
  ankr: "ankr",
  woo: "woo network",
  kava: "kava kava labs",
  osmo: "osmosis",
  jst: "just tron",
  sun: "sun token tron",
  win: "winklink tron",
  btt: "bittorrent",
  nft: "apenft",
  blur: "blur marketplace",
  looks: "looksrare",
  x2y2: "x2y2",
  rari: "rarible",
  super: "superverse",
  prime: "echelon prime",
  ilv: "illuvium",
  ygg: "yield guild",
  alice: "my neighbor alice",
  tlm: "alien worlds",
  slp: "smooth love potion axie",
  c98: "coin98",
  ray: "raydium",
  srm: "serum",
  fida: "bonfida",
  maps: "maps me",
  kin: "kin",
  orca: "orca solana",
  step: "step finance",
  media: "media network",
  polis: "polis",
  hnt: "helium",
  mobile: "helium mobile",
  iot: "helium iot",
  scrt: "secret network secret",
  dvpn: "sentinel dvpn",
  akt: "akash network akash",
  regen: "regen network",
  btsg: "bitsong",
  dydx: "dydx exchange",
  gmx: "gmx arbitrum",
  perp: "perpetual protocol",
  joe: "trader joe",
  png: "pangolin",
  spirit: "spiritswap",
  boo: "spookyswap",
  beets: "beethoven x",
  rai: "rai reflex bond",
  fei: "fei protocol",
  tribe: "fei tribe",
  alcx: "alchemix",
  fxs: "frax share",
  fpi: "frax price index",
  cvx: "convex finance",
  spell: "abracadabra spell token",
  mim: "magic internet money",
  ice: "popsicle finance",
  badger: "badger dao",
  lqty: "liquity lqty",
  tru: "truefi",
  mpl: "maple finance",
  gold: "gold commodity",
  silver: "silver commodity",
  oil: "oil commodity",
};

function normId(iconId: string) {
  return iconId.toLowerCase();
}

/** True if `queryLower` matches the slug or any registered name/tag text for this icon. */
export function cryptoIconMatchesNameSearch(iconId: string, queryLower: string): boolean {
  const idl = normId(iconId);
  if (idl.includes(queryLower)) return true;
  const tags = ICON_NAME_TAGS[idl];
  return Boolean(tags && tags.includes(queryLower));
}

/** True when the match is via name/tag text only (not substring of slug). */
export function cryptoIconTagHit(iconId: string, queryLower: string): boolean {
  const idl = normId(iconId);
  if (idl.includes(queryLower)) return false;
  const tags = ICON_NAME_TAGS[idl];
  return Boolean(tags && tags.includes(queryLower));
}
